name: Build KROP APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { java-version: '17', distribution: 'temurin' }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install Cordova & Build
        run: |
          npm install -g cordova
          npm install
          cordova platform add android
          # Собираем дебаг версию, её проще найти
          cordova build android
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: krop-final-apk
          # Вот тут мы исправили путь на более точный!
          path: platforms/android/app/build/outputs/apk/debug/*.apk
